### PR TITLE
Issue #50 Deleting an instance of the authentication module registered by default also deletes the authentication modules of the same type

### PR DESCRIPTION
**Pull request by ksuzukiTVDn1**
## Solution

previous code remove all of config tree when remove default module or same name of default module.

new delete process first check if target module is  subConfig.
if module is not subConfig, check target module is default module.
finally, check if default module have subConfig. not have subConfig remove default module config tree.
if module have subConfig remove default module setting only.

if target module is not default but same name of default module, remove that when first check timing.

## Testing

a.
1. Create a new module instance with a default module
2. Delete default module instance

b.
1. Delete default module instance
2. Create a new module instance same name of default module
3. Delete 2. instance

### previous pullrequest comment reply

> We already have a patch for this problem, right?

yes. but that patch is not good.(patch include OPENAM-9156 fix,I want to fix that another pull request)

> I can not understand why you ignore the patch (including the background of the creation) and try to create it.
> By the way, according to CERT Secure Coding Standards, do not catch NPE.

1. isDefaultCreatedAuthModule is not need change
Previous patch is changed isDefaultCreatedAuthModule method  to check same name of default module.
But that change is not need. (often destructive change for another methods)
That fix need OPENAM-9156, not this issue.

2. mysterious null pointer check
previous patch do null-check to config.getSubConfigNames.
but config.getSubConfigNames is this code

* ServiceConfig.java

```
public Set<String> getSubConfigNames() throws SMSException {
validateServiceConfigImpl();
try {
return sc.getSubConfigNames(token);
} catch (SSOException s) {
SMSEntry.debug.error("ServiceConfig: Unable to "
+ "get subConfig Names", s);
}
return (Collections.EMPTY_SET);
}
```

its always return some of set object. not need null check.

### CODE REVIEW

**Comment by tsujiguchitky** [comment]
>yes. but that patch is not good.(patch include OPENAM-9156 fix,I want to fix that another pull request)

OK, I see.
Well, I hope you will fix OPENAM-9156 separately.

**Comment by tsujiguchitky** [comment]
> its always return some of set object. not need null check.

Hm.
Certainly, if the design is correct, null checks will not be necessary. 
However, to be sure that the method does not return null, it is necessary to check `getSubConfigNames (SSOToken)` and the method called there.
If it is uneasy, I will often choose a safe side(null check).

**Comment by tsujiguchitky** [comment]
> isDefaultCreatedAuthModule is not need change

In my image, it is strange that this method returns true for a re-created module with the same name as the default. 
Because this method determines by module name whether it is a default module or not. I wonder this method is enough.

**Comment by ksuzukiTVDn1** [comment]
> In my image, it is strange that this method returns true for a re-created module with the same name as the default. 
> Because this method determines by module name whether it is a default module or not. I wonder this method is enough.

if delete method can determine if target module and default module are the same, then this fix shuld change delete method only.

"method returns true for a re-created module with the same name as the default" is different matter.(fix in OPENAM-9156)

**Comment by ksuzukiTVDn1** [comment]
> Hm.
> Certainly, if the design is correct, null checks will not be necessary.
> However, to be sure that the method does not return null, it is necessary to check 
> getSubConfigNames (SSOToken) and the method called there.
> If it is uneasy, I will often choose a safe side(null check).

if getSubConfigNames is able to return null, that method shuld change name getSubConfigNamesOrNull().

I understand your concerns, but previous patch's code is it 

```
+            if (isDefaultCreatedAuthModule(resourceId, config)) {
+                Set<String> subConfigNames = config.getSubConfigNames();
+                if (subConfigNames == null || subConfigNames.size() == 0) {
+                    scm.removeOrganizationConfiguration(realmFor(context), null);
+                } else {
+                    Map attrs = config.getAttributesWithoutDefaults();
+                    if (attrs != null) {
+                        config.removeAttributes(attrs.keySet());
+                    }
+                }
```

if getSubConfigNames return null, remove all of same type module of target module.
It's not good Behavior.




please see it
https://www.yegor256.com/2014/05/13/why-null-is-bad.html

**Comment by tsujiguchitky** [comment]
> if delete method can determine if target module and default module are the same, then this fix shuld change delete method only.

I understood the opinion that you want to narrow the scope of the impact.

> "method returns true for a re-created module with the same name as the default" is different matter.(fix in OPENAM-9156)

OK.

**Comment by tsujiguchitky** [comment]
> if getSubConfigNames return null, remove all of same type module of target module.
> It's not good Behavior.

good point.

**Comment by tsujiguchitky** [comment]
Please add the copyright to the source code header.

**Comment by tsujiguchitky** [comment]
LGTM

**Pull request merged**
