### PR TITLE
Issue #62 WebAuthn Authentication Module

### PR DESCRIPTION
**Pull request by tsujiguchitky**
## Analysis

See #62 "Description".

## Solution

1. Add two authentication modules baseed on [Web Authentication specification](https://www.w3.org/TR/webauthn/)
    * `WebAuthn (Register)` is used for WebAuthn device registration
    * `WebAuthn (Authenticate)` performs authentication using WebAuthn device

2. Add a new service that configures the LDAP server where devices are stored

3. Add WebAuthn device LDAP schema to embedded DJ (For test use)

4. Add WebAuthn device management GUI to user dashboard

## Install/Update

The simple usage is shown below.

### How to set up

1. Perform initial configuration of OpenAM
    * The built-in DJ is used here as a storage location for users and devices.
2. Make OpenAM accessible via HTTPS
3. Add `WebAuthn Authenticator Service` in Admin Screen
    * Log in as `amadmin`
    * Move to `Target Realm > Services`
    * Click `Add a Service` button
    * Enter module name and select `WebAuthn Authenticator Service`
    * Enter the password of "cn=Directory Manager" for the bind password
4. Add `WebAuthn (Registration)` module in Admin screen
    * Move to `Target realm > Authentication > Modules`
    * Click `Add Module` button and select `WebAuthn (Registration)`, then click `Create` button
 * Modify Origin to OpenAM host if necessary
5. Create an authentication chain include data store authentication and "WebAuthn (registration)"
    * Move to `Target realm > Authentication > Chains`
    * Click `Add Chain` button and enter chann name, then click `Create` button
    * Click `Add Module` button and select `Data Store` module as `Requisite`, then click `OK` button
    * Click `Add Module` button and select `WebAuthn (Registration)` module as `Required`, then click `OK` button
    * Click `Save Changes` button
6. Add `WebAuthn (Authentication)` module in Admin screen
    * Move to `Target realm > Authentication > Modules`
    * Click `Add Module` button and select `WebAuthn (Authenticate)`, then click `Create` button
    * Modify Origin to OpenAM host if necessary

### How to use

1. Call the authentication chain created in setup procedure 5 to register the WebAuthn device
2. Call the authentication module created in setup procedure 6, and authenticate with the FIDO device

## Compatibility

N/A

## Performance

N/A

## I18N

Only English and Japanese screens are supported.

## Testing

* Use Case
  * Password-less authentication (MFA=false / Resident Key=false)
  * Multi-factor authentication (MFA=true / Resident Key=false)
  * Username-less authentication (MFA=false / Resident Key=true)

* Device management
  * Display devices on dashboard screen
  * Delete devices on dashboard screen

* Combination with sub realm
  * Registration
  * Authentication
  * Device management

* Authenticator data store
  * Embeded OpenDJ
  * External LDAP(OpenLDAP)

## Regression testing

N/A

### CODE REVIEW

**Comment by ogis-miyamura** [comment]
Every use case worked fine.

Although it is trivial, there are two points to consider.

1. Probably a typo, in a total of 4 `*.properties` files
    - `Attachiment` -> `Attachment`

2. Extra space at the end of line (if easy to fix)
    - Regular expression we used to check: `[^ *] +$` -> 10 files / 242 locations

**Comment by tsujiguchitky** [comment]
> Although it is trivial, there are two points to consider.

Thank you for your review.
I will fix them.

**Comment by tsujiguchitky** [comment]
> 1. Probably a typo, in a total of 4 *.properties files

I'm sorry, I found only two files. 

`amAuthWebAuthnRegister.properties`, `amAuthWebAuthnRegister_ja.properties`, and which files are the rest?

**Comment by ogis-miyamura** [comment]
> I'm sorry, I found only two files.
> `amAuthWebAuthnRegister.properties`, `amAuthWebAuthnRegister_ja.properties`, and which files are the rest?

Sorry, my confirmation was incorrect.
The two files presented are correct.

**Comment by tsujiguchitky** [comment]
> The two files presented are correct.

OK. Thanks!

**Comment by tsujiguchitky** [comment]
> Although it is trivial, there are two points to consider.

Fixed.

**Comment by ogis-miyamura** [comment]
ありがとう、それは完全に修正されました。
LGTM

**Pull request merged**
