### PR TITLE
Issue #228 ConfigureGoogleApps remove configured 'unspecified' NameID value map

### PR DESCRIPTION
**Pull request by idm-kiyoshi**
## Analysis

hosted idp properties is updated when we configure GoogleApps(Google Workspace) as remote sp.

## Solution

Remove updateIDPMeta in ConfigureGoogleApps

## Install/Update

None

## Compatibility

None

## Performance

None

## I18N

None

## Testing

1. Create Hosted Identity Provider
1. Setting ` unspecified ` NameID-Format map value.  Ex.) ` urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified=mail `
1. Configure GoogleApps
1. Check NameID-Format map value is not updated

## Regression testing

- [x] Verify OpenAM and Google can authenticate with SAML using ConfigureGoogleApps

### CODE REVIEW

**Comment by tsujiguchitky** [comment]
Hi @idm-kiyoshi 

Thank you for the contribution.

I noticed two points, so please check the following.

* Some import statements are unused
* `nameidMapping` variable is no longer in use.

**Comment by idm-kiyoshi** [comment]
@tsujiguchitky 
Thank you for your review.
I fixed about your review comment.

**Comment by tsujiguchitky** [comment]
LGTM

**Comment by OGIS-ShionOsada** [comment]
That's a nice code. We have done a test and code review and have nothing to point out.

**Review by OGIS-ShionOsada — APPROVED** [review]

**Review by ogis-miyamura — APPROVED** [review]

**Pull request merged**
