### PR TITLE
Issue #50 Deleting an instance of the authentication module registered by default also deletes the authentication modules of the same type

### PR DESCRIPTION
**Pull request by ksuzukiTVDn1**
## Behavior

When deleting a default module, it is always remove all same module 

## Solution

Add a check that has no other module exists when the target module is default

## Testing

a. 
    1. Create a new module instance with a default module
    2. Delete default module instance

b.
    1. Delete default module instance
    2. Create a new module instance same name of default module
    3. Delete 2. instance

### CODE REVIEW

**Comment by tsujiguchitky** [comment]
If you create an instance with the same name as the default authentication module, you can not delete it.

Please check the following steps.

1. Delete default HOTP module instance
2. Create a HOTP module with the same name as the default
3. Delete the module of step 2

**Comment by tsujiguchitky** [comment]
>## Analysis
> When deleting a default module, it is always remove all same module

This is a behavior, not an analysis.

**Comment by ksuzukiTVDn1** [comment]
fixed patch probrem

isDefaultCreatedAuthModule return true  when module name is default name. 
I changed the order subConfig check to first.

**Comment by tsujiguchitky** [comment]
We already have a patch for this problem, right?

I can not understand why you ignore the patch (including the background of the creation) and try to create it.

By the way, according to `CERT Secure Coding Standards`, do not catch NPE.

See  https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors

**Comment by tsujiguchitky** [comment]
Continue to #100

**Pull request closed without merging**
