### PR TITLE
Issue #135 Branding

### PR DESCRIPTION
**Pull request by tsujiguchitky**
## Analysis

We forked ForgeRock OpenAM as OpenAM Consortium edition.
However, our OpenAM screen remains ForgeRock brand.
We should resolve this before a new release of OpenAM Consortium edition.

## Solution

* Replace favicon
* Replace logo
* Change image colors
* Update the copyright notice on the screen
* Change the default root suffix

This fix depends on openam-jp/forgerock-ui#3 .

### CODE REVIEW

**Comment by ogis-miyamura** [comment]
1. The logo on the left side of the initial setting / upgrade screen disappears.
I cannot judge whether it is intentional.
I think that there is no problem even if there is no logo here.

1. When press the `Version` button on a non-XUI screen, the dialog copyright remains `Forgerock AS`.

**Comment by tsujiguchitky** [comment]
> 1. The logo on the left side of the initial setting / upgrade screen disappears.

The screen I am supposing is the following. Do you know why the logo is not displayed in your environment (for example, no image is placed)?

Setup

**Comment by tsujiguchitky** [comment]
>2. When press the Version button on a non-XUI screen, the dialog copyright remains Forgerock AS.

In my environment, the screen looks like this. Did you build on the latest branch? The copyright is fixed in bfaea93748b4e604c708c01bf3be44e1e29001a6.

Version

**Comment by ogis-miyamura** [comment]
I'm sorry. There seems to be a problem with our verification procedure.
I will check it again.

**Comment by tsujiguchitky** [comment]
> I will check it again.

Thank you for the review. 
Sorry to trouble you, but please continue to review.

**Comment by ogis-miyamura** [comment]
After removing Tomcat and WEB browser cache, there was no problem.
I'm sorry for misunderstanding.

**Pull request merged**
